# Generated by Django 6.0.4 on 2026-04-28 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacjent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identyfikator_pacjenta', models.CharField(max_length=100, unique=True)),
                ('rok_urodzenia', models.IntegerField()),
                ('plec', models.CharField(max_length=10)),
                ('lekarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacjenci', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Badanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sciezka_do_pliku', models.TextField()),
                ('data_wgrania', models.DateTimeField(auto_now_add=True)),
                ('pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badania', to='db_models.pacjent')),
            ],
        ),
        migrations.CreateModel(
            name='WynikAnalizyAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prawdopodobienstwo_choroby', models.FloatField(help_text='W %')),
                ('badanie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wynik_ai', to='db_models.badanie')),
            ],
        ),
        migrations.CreateModel(
            name='RaportKoncowy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notatki_lekarza', models.TextField()),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('wynik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raport', to='db_models.wynikanalizyai')),
            ],
        ),
    ]
